@startuml change_settings_activity

title Change Settings Activity Diagram

start

:UserLogin;
:Go to Settings;
if (Change Theme?) then (yes)
  :Select Theme;
  :Save Settings;
else (no)
  if (Update User Info) then (yes)
    :Update User Info;
    :Save Settings;
  else (no)
  endif
endif

stop
@enduml